### ISSUE TITLE
Input background should be white instead of transparent

### ISSUE THREAD

**Issue by matthieuh** [containous/faency#23]
<img width="219" alt="Screen Shot 2019-12-19 at 10 48 29" src="https://user-images.githubusercontent.com/1550192/71163318-1f3ae100-224d-11ea-81a1-480e9dfa5638.png">
instead of
<img width="224" alt="Screen Shot 2019-12-19 at 10 48 34" src="https://user-images.githubusercontent.com/1550192/71163322-219d3b00-224d-11ea-8cc9-377bc688a4a5.png">

**Comment by paulocfjunior** [comment]
Fixed by https://github.com/containous/faency/pull/27
