### ISSUE TITLE
SubNab background should be white instead of transparent

### ISSUE THREAD

**Issue by matthieuh** [containous/faency#24]
<img width="550" alt="Screen Shot 2019-12-19 at 10 49 34" src="https://user-images.githubusercontent.com/1550192/71163375-44c7ea80-224d-11ea-8540-8e699c7c5f5e.png">
instead of
<img width="635" alt="Screen Shot 2019-12-19 at 10 49 29" src="https://user-images.githubusercontent.com/1550192/71163373-42fe2700-224d-11ea-8663-930c4d88d41f.png">

**Comment by paulocfjunior** [comment]
Fixed by https://github.com/containous/faency/pull/27
